objects/Object_A__c/Object_A__c.object-meta.xml
<CustomObject>
    <description>Natixis challenge</description>
    <label>Object A</label>
    <nameField>
        <displayFormat>A-{000}</displayFormat>
        <label>Object A Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>A Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Object_B__c/Object_B__c.object-meta.xml
<CustomObject>
    <description>Natixis Challenge</description>
    <label>Object B</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Object B Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>B Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Object_B__c/fields/Object_A__c.field-meta.xml
<CustomField>
    <fullName>Object_A__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Object A</label>
    <referenceTo>Object_A__c</referenceTo>
    <relationshipLabel>B Objects</relationshipLabel>
    <relationshipName>B_Objects</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Object_C__c/Object_C__c.object-meta.xml
<CustomObject>
    <description>Natixis challenge</description>
    <label>Object C</label>
    <nameField>
        <displayFormat>C-{000}</displayFormat>
        <label>Object A Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>C Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Object_C__c/fields/Object_B__c.field-meta.xml
<CustomField>
    <fullName>Object_B__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Object B</label>
    <referenceTo>Object_B__c</referenceTo>
    <relationshipLabel>C Objects</relationshipLabel>
    <relationshipName>C_Objects</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/NatixisChallengeControllerTest.cls
@isTest
private class NatixisChallengeControllerTest {
	
    @testSetup static void setup(){
    	Object_A__c a_record = new Object_A__c();
    	insert a_record;
        Object_B__c b_record_1 = new Object_B__c(Object_A__c=a_record.id);
        insert b_record_1;
        Object_C__c c_record_1 = new Object_C__c(Object_B__c=b_record_1.id);
        insert c_record_1;
        Object_C__c c_record_2 = new Object_C__c(Object_B__c=b_record_1.id);
        insert c_record_2;
    }
    
    static testMethod void testingController(){
        List<Object_A__c> a_record = [select id from Object_A__c];        
        List<Object> ChildAndGrandchilds = NatixisChallengeController.getRelatedRecords(a_record[0].id);
        List<Object_B__c> b_records_lst = [select id from Object_B__c where Object_A__c =: a_record[0].id];
        system.assertEquals(1, b_records_lst.size());
        List<String> str_lst = new List<String>();
        List<Object> moreChildAndGrandchilds = NatixisChallengeController.getMoreRelatedRecords(a_record[0].id, str_lst);
        
        system.assertEquals(3, ChildAndGrandchilds.size());
    }
}